# Generated by Django 4.2.1 on 2023-05-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='city',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
